In [ ]:
import numpy as np

# Criando NumPy Arrays

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

##Métodos de Construção

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0,10,51)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##Numeros Random

In [ ]:
np.random.rand(3) #amostra aleatoria de 0 a 1

array([0.20165274, 0.45020828, 0.73833525])

In [ ]:
np.random.rand(5,5)

array([[0.20673194, 0.62059456, 0.51047865, 0.23256249, 0.25270404],
       [0.97458298, 0.14347657, 0.7847169 , 0.47297013, 0.25276354],
       [0.44792082, 0.89351302, 0.23741744, 0.22765345, 0.6016376 ],
       [0.70273966, 0.45155946, 0.72083348, 0.41708112, 0.26439251],
       [0.29954595, 0.62539272, 0.56108334, 0.6965511 , 0.19233945]])

In [ ]:
np.random.randn(3) # centrada em zero

array([-1.28989399,  1.02400763, -0.7182271 ])

In [ ]:
np.random.randn(5,5)

array([[ 0.55609288, -0.05590019, -0.67085165, -0.893409  ,  0.23315945],
       [-1.29653276, -1.05556316,  0.15335836,  1.5310759 , -0.9598847 ],
       [-0.40788731, -0.30574823, -0.72278337, -0.50747791, -0.63065595],
       [ 0.36217128,  0.39557047, -0.20079198,  0.90935049,  0.18952563],
       [ 0.33255731, -0.04743678,  0.12969398, -1.45972366, -0.97893148]])

In [ ]:
np.random.randint(1,100)

14

In [ ]:
np.random.randint(1,100,200)

array([98, 34, 62, 56, 17,  2, 20,  4, 30, 50, 40, 25, 70, 75, 42, 73, 76,
       99, 40, 21, 73, 70,  7, 20, 65, 67, 28, 16,  2, 67,  7, 69, 85, 35,
       13, 30, 87, 27, 68, 94, 14, 62, 20, 64, 25, 93, 75, 11,  9, 37, 69,
       45, 72, 66, 78, 95, 94, 35, 34, 97, 84, 91, 95, 56, 17,  2, 41, 34,
       55, 37, 11,  3, 85, 43,  7, 48, 69, 25, 31, 61, 42,  6, 73, 28, 13,
       80, 49, 17, 18, 86, 76, 63, 61, 27, 71, 59, 14, 80,  2, 29, 97, 51,
       86, 46, 65, 97,  4, 32, 60, 21, 35, 87, 94, 17, 82, 21, 27, 27, 88,
       63, 64, 45, 72, 10, 42, 23, 31, 20, 47, 93, 95, 99, 97, 41, 78, 74,
       29, 31, 25, 29, 54, 22,  6, 32,  3, 81, 37, 55, 26, 62, 42, 35, 98,
       83, 14, 28, 54, 86,  1, 83, 63, 49, 99, 26, 10, 75, 72,  2, 49, 38,
       86, 29, 62, 90, 27, 94, 64, 85, 42, 99, 20, 51,  5, 87,  2, 61, 41,
        4,  5, 19, 20, 55,  2, 58,  9, 34, 99, 20, 31, 54])

##Atributos e Métodos das Arrays

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([39,  8, 30, 47,  5, 32,  6,  4, 27, 27])

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
ranarr

array([39,  8, 30, 47,  5, 32,  6,  4, 27, 27])

In [ ]:
ranarr.max()

47

In [ ]:
ranarr.argmax()

3

In [ ]:
ranarr.min()

4

In [ ]:
ranarr.argmin()

7

In [ ]:
#vetor
arr.shape

(25,)

In [ ]:
#perceba os 2 pares de colchetes
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.dtype

dtype('int64')

#Indexação e Seleção

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr[8]

8

In [ ]:
arr[2:5]

array([2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
slice_of_arr = arr [0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr = arr [:] = 99
slice_of_arr

99

In [ ]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

##Indexando um array 2D (matrizes)

In [ ]:
##obs : o formato geral é arr_2d [row, col]
arr_2d = np.array(([5,10,15],[20,25,30], [35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [ ]:
arr_2d[1]

array([20, 25, 30])

In [ ]:
arr_2d[1,0]

20

In [ ]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
arr_2d[:,2]

array([15, 30, 45])

In [ ]:
#Indexação Sofisticada (Fancy Indexing)
arr2d = np.zeros((10,10))

arr_length = arr2d.shape[1]

for i in range(arr_length):
  arr2d[i] = i

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [ ]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [ ]:
#Em qualquer ordem
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [ ]:
##Seleção

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = 2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Operações no Numpy

##Aritmética

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Aviso na divisão por zero
arr/arr


<ipython-input-147-933f43cf19bd>:2: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#Novamente aviso na divisão por zero
1/arr

<ipython-input-148-302a422b0516>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Funções Universais

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
np.max(arr) #o mesmo que arr.max()

9

In [ ]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
np.log(arr)

<ipython-input-155-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])